name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: | 
            Changes in this Release
            - First Change
            - Second Change
        with:
          draft: false
          prerelease: false
